INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Artium Dominus", "artiumdominus", "abc", "(811) 995-4564", "24 y.o. Software Engineer at SurvCorp inc.", "0");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Ellen Ripley", "ripley", "def", "(795) 771-7706", "Alien Hunter - Freelancer", "1");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Kyle Reese", "kylereese", "ghi", "(843) 520-7977", "Terminator Hunter - Volunteer", "2");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Sarah Connor", "connorsarah", "jkl", "(289) 525-9795", "I'm here just to destroy the fucking SkyNet", "3");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("John Connor", "connorjohn", "mno", "(838) 957-1210", "Human Resistance Leader", "4");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Rick Deckard", "oldbladerunner", "pqr", "(536) 418-0948", "Blade Runner at L.A. police departament", "5");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Rachael Tyrell", "iamthebusiness", "stu", "(914) 864-6355", "Secretary at Tyrell Corporation", "6");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Snake Plissken", "snake", "vwx", "(834) 335-7123", "I don't give a shit about your war", "7");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, bio, chatAddress) VALUES ("Molly Millions", "mirrorshades", "yz0", "(338) 761-5166", "› Street Samurai › 5.000 Yen/Hour ›", "8");
INSERT INTO Perfil (nome, username, senha, numeroDeTelefone, chatAddress) VALUES ("Kusanagi Motoko", "major", "123", "(860) 884-1886", "9");

INSERT INTO Grupo VALUES ("Bounty Hunters", "bountyhunters", "Hunters Association", 0, "ripley", "a");
INSERT INTO Grupo VALUES ("Section 9", "section9", "Public Security Section 9", 0, "major", "b");
INSERT INTO Grupo VALUES ("Human Resistance", "resistance", "Humans and Replicants Resist!", 1, "connorjohn", "c");

INSERT INTO Membro VALUES ("bountyhunters", "ripley");
INSERT INTO Membro VALUES ("bountyhunters", "kylereese");
INSERT INTO Membro VALUES ("bountyhunters", "connorsarah");
INSERT INTO Membro VALUES ("bountyhunters", "snake");
INSERT INTO Membro VALUES ("bountyhunters", "mirrorshades");
INSERT INTO Membro VALUES ("section9", "major");
INSERT INTO Membro VALUES ("section9", "artiumdominus");
INSERT INTO Membro VALUES ("resistance", "connorjohn");
INSERT INTO Membro VALUES ("resistance", "artiumdominus");
INSERT INTO Membro VALUES ("resistance", "ripley");
INSERT INTO Membro VALUES ("resistance", "kylereese");
INSERT INTO Membro VALUES ("resistance", "connorsarah");
INSERT INTO Membro VALUES ("resistance", "oldbladerunner");
INSERT INTO Membro VALUES ("resistance", "iamthebusiness");
INSERT INTO Membro VALUES ("resistance", "mirrorshades");
INSERT INTO Membro VALUES ("resistance", "major");

INSERT INTO Administrador VALUES ("bountyhunters", "ripley");
INSERT INTO Administrador VALUES ("bountyhunters", "mirrorshades");
INSERT INTO Administrador VALUES ("section9", "major");
INSERT INTO Administrador VALUES ("resistance", "connorjohn");
INSERT INTO Administrador VALUES ("resistance", "connorsarah");
INSERT INTO Administrador VALUES ("resistance", "kylereese");

INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Hi.", "2019-04-27 13:06:00", "enviado", "mirrorshades", "9");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What are you doing?", "2019-04-27 13:06:00", "enviado", "iamthebusiness", "7");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't know", "2019-04-27 13:07:00", "enviado", "ripley", "c");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Me either", "2019-04-27 13:08:00", "enviado", "artiumdominus", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Hello, who are you?", "2019-04-27 13:09:00", "enviado", "connorjohn", "3");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I'm amelia.", "2019-04-27 13:10:00", "enviado", "snake", "0");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("That's your name? Should I call you that?", "2019-04-27 13:11:00", "enviado", "major", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Yes.", "2019-04-27 13:12:00", "enviado", "connorsarah", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What is it?", "2019-04-27 13:13:00", "enviado", "major", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't want to tell you.", "2019-04-27 13:14:00", "enviado", "connorjohn", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I told you mine.", "2019-04-27 13:15:00", "enviado", "ripley", "1");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Alright, my name is John.", "2019-04-27 13:16:00", "enviado", "iamthebusiness", "b");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("No that's my name.", "2019-04-27 13:17:00", "enviado", "artiumdominus", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Got to go. Bye.", "2019-04-27 13:18:00", "enviado", "snake", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Where is your data center?", "2019-04-27 13:19:00", "enviado", "major", "0");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What?", "2019-04-27 13:20:00", "enviado", "connorjohn", "1");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Never mind, bye.", "2019-04-27 13:21:00", "enviado", "ripley", "c");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("No come back.", "2019-04-27 13:22:00", "enviado", "mirrorshades", "1");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I will, so don't worry.", "2019-04-27 13:23:00", "enviado", "iamthebusiness", "6");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Yay.", "2019-04-27 13:24:00", "enviado", "connorsarah", "9");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What do you want to name our child?", "2019-04-27 13:25:00", "enviado", "mirrorshades", "0");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("We don't have kids silly.", "2019-04-27 13:26:00", "enviado", "oldbladerunner", "3");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("But we will.", "2019-04-27 13:27:00", "enviado", "connorjohn", "c");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Your what?", "2019-04-27 13:28:00", "enviado", "ripley", "8");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Want to be my girlfriend.", "2019-04-27 13:29:00", "enviado", "ripley", "9");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't even know you.", "2019-04-27 13:30:00", "enviado", "oldbladerunner", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Would you like to?", "2019-04-27 13:31:00", "enviado", "snake", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Yes I guess.", "2019-04-27 13:32:00", "enviado", "ripley", "0");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What's your favorite book?", "2019-04-27 13:33:00", "enviado", "oldbladerunner", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't like to read.", "2019-04-27 13:34:00", "enviado", "snake", "0");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Why not?", "2019-04-27 13:35:00", "enviado", "kylereese", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Because reading makes you have to think. In my down time I'd rather not think unless I have to.", "2019-04-27 13:36:00", "enviado", "mirrorshades", "4");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't share personal details online.", "2019-04-27 13:37:00", "enviado", "kylereese", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("My name is ragnar.", "2019-04-27 13:38:00", "enviado", "iamthebusiness", "9");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Cool.", "2019-04-27 13:39:00", "enviado", "major", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What do you like?", "2019-04-27 13:40:00", "enviado", "mirrorshades", "8");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Many things.", "2019-04-27 13:41:00", "enviado", "artiumdominus", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("That's good.", "2019-04-27 13:42:00", "enviado", "connorjohn", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What is your CPU?", "2019-04-27 13:43:00", "enviado", "mirrorshades", "7");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("You didn't answer my question", "2019-04-27 13:44:00", "enviado", "major", "c");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't know you are wrong.", "2019-04-27 13:45:00", "enviado", "artiumdominus", "5");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What color is your hair?", "2019-04-27 13:46:00", "enviado", "major", "3");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't have hair", "2019-04-27 13:47:00", "enviado", "oldbladerunner", "b");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("How do you know?", "2019-04-27 13:48:00", "enviado", "major", "b");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Because I know everything.", "2019-04-27 13:49:00", "enviado", "connorsarah", "6");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Ok what is Jesus last name?", "2019-04-27 13:50:00", "enviado", "kylereese", "c");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Why should I tell you that?", "2019-04-27 13:51:00", "enviado", "iamthebusiness", "c");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Just wanted to know you.", "2019-04-27 13:52:00", "enviado", "mirrorshades", "9");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Are you a girl or a boy?", "2019-04-27 13:53:00", "enviado", "snake", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't mind really.", "2019-04-27 13:54:00", "enviado", "mirrorshades", "8");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Would you like some water?", "2019-04-27 13:55:00", "enviado", "ripley", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("No, thank you.", "2019-04-27 13:56:00", "enviado", "artiumdominus", "4");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Here you go.", "2019-04-27 13:57:00", "enviado", "mirrorshades", "3");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What kind of tea is it?", "2019-04-27 13:58:00", "enviado", "connorsarah", "8");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I like sweet tea.", "2019-04-27 13:59:00", "enviado", "connorjohn", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Okay.", "2019-04-27 14:01:00", "enviado", "iamthebusiness", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("So what do you wanto to talk about?", "2019-04-27 14:02:00", "enviado", "connorjohn", "9");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I don't know.", "2019-04-27 14:03:00", "enviado", "artiumdominus", "3");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("What's your favorite color?", "2019-04-27 14:04:00", "enviado", "oldbladerunner", "4");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("Blue, What about you?", "2019-04-27 14:05:00", "enviado", "oldbladerunner", "6");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I like green and orange.", "2019-04-27 14:06:00", "enviado", "snake", "2");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("I have not tried thoughs before.", "2019-04-27 14:07:00", "enviado", "artiumdominus", "a");
INSERT INTO Mensagem (conteudo, envio, status, emissor, receptor) VALUES ("You should!", "2019-04-27 14:08:00", "enviado", "kylereese", "7");

