# Generated by Django 2.1.7 on 2019-06-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='background_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
