# Generated by Django 2.1.7 on 2019-06-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190610_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('0', 'Rascunho'), ('1', 'Enviado'), ('2', 'Entregue'), ('3', 'Visualizado')], default='0', max_length=1),
        ),
    ]
